### ISSUE TITLE
ServerInfo Command Embed field error

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#1]
### Repository

Mops-Bot

### Bug type

Commands

### Description of the bug?

MessageEmbed field is undefined ( Line 18:14 serverinfo.js ) 

dev!serverinfo = Embed containing server info

### Relevant log output

```shell
[antiCrash] :: Unhandled Rejection/Catch
RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.
    at Function.verifyString (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\util\Util.js:416:41)
    at Function.normalizeField (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:544:19)
    at C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:565:14
    at Array.map (<anonymous>)
    at Function.normalizeFields (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:564:8)
    at MessageEmbed.addFields (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:328:42)
    at MessageEmbed.addField (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:319:17)
    at Object.run (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\commands\util\serverInfo.js:18:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\events\messageCreate.js:69:9) {
  [Symbol(code)]: 'EMBED_FIELD_VALUE'
} Promise {
  <rejected> RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.
      at Function.verifyString (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\util\Util.js:416:41)
      at Function.normalizeField (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:544:19)
      at C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:565:14
      at Array.map (<anonymous>)
      at Function.normalizeFields (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:564:8)
      at MessageEmbed.addFields (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:328:42)
      at MessageEmbed.addField (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\discord.js\src\structures\MessageEmbed.js:319:17)
      at Object.run (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\commands\util\serverInfo.js:18:14)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Client.<anonymous> (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\events\messageCreate.js:69:9) {
    [Symbol(code)]: 'EMBED_FIELD_VALUE'
  }
}
```

**Comment by OnlyTunes** [comment]
Fixed in latest push:

https://github.com/OnlyTunesRadio/Mops-Bot/commit/449cbe311c4a706fdfb56bd6f703d4d987f191ae
