### ISSUE TITLE
Possible bug caused by new spotify blend playlists

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#24]
### Repository

Mops-Bot

### Bug type

Slash Commands

### Description of the bug?

Json decode error at position 0 during parsing response from Spotify blend link

### Relevant log output

```shell
[antiCrash] :: Unhandled Rejection/Catch
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (B:\DEVELOPMENT\Mops-Bot\node_modules\petitio\dist\index.js:30:574)
    at ke.json (B:\DEVELOPMENT\Mops-Bot\node_modules\petitio\dist\index.js:30:2499)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async kazagumoSpotify.refreshToken (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSpotify.js:38:46)
    at async kazagumoSpotify.request (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSpotify.js:28:13)
    at async kazagumoSearch.getPlaylistTracks (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSearch.js:95:25)
    at async kazagumoSearch.search (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSearch.js:40:44)
    at async kazagumoPlayer.search (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoPlayer.js:161:16)
    at async play (B:\DEVELOPMENT\Mops-Bot\SlashCommandFunctions\music\players\play.js:28:19) Promise {
  <rejected> SyntaxError: Unexpected token u in JSON at position 0
      at JSON.parse (<anonymous>)
      at Y.json (B:\DEVELOPMENT\Mops-Bot\node_modules\petitio\dist\index.js:30:574)
      at ke.json (B:\DEVELOPMENT\Mops-Bot\node_modules\petitio\dist\index.js:30:2499)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async kazagumoSpotify.refreshToken (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSpotify.js:38:46)
      at async kazagumoSpotify.request (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSpotify.js:28:13)
      at async kazagumoSearch.getPlaylistTracks (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSearch.js:95:25)
      at async kazagumoSearch.search (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoSearch.js:40:44)
      at async kazagumoPlayer.search (B:\DEVELOPMENT\Mops-Bot\node_modules\kazagumo\src\kazagumoPlayer.js:161:16)
      at async play (B:\DEVELOPMENT\Mops-Bot\SlashCommandFunctions\music\players\play.js:28:19)
}
```

**Comment by OnlyTunes** [comment]
closing due to moving to new LL module
