### ISSUE TITLE
Shuffle slash command error

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#26]
### Repository

Mops-Bot

### Bug type

Slash Commands

### Description of the bug?

channels undefined when calling shuffle command

### Relevant log output

```shell
[antiCrash] :: Unhandled Rejection/Catch
TypeError: Cannot read properties of undefined (reading 'channel')
    at shuffle (B:\DEVELOPMENT\Mops-Bot\SlashCommandFunctions\music\players\shuffle.js:12:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (B:\DEVELOPMENT\Mops-Bot\SlashCommands\music\music.js:164:25) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'channel')
      at shuffle (B:\DEVELOPMENT\Mops-Bot\SlashCommandFunctions\music\players\shuffle.js:12:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.run (B:\DEVELOPMENT\Mops-Bot\SlashCommands\music\music.js:164:25)
}
```

**Comment by OnlyTunes** [comment]
Fixed in latest commit:

https://github.com/OnlyTunesRadio/Mops-Bot/commit/691573b1f601c83afd1df81521f231a53cc1e734
