### ISSUE TITLE
Username undefined on all TTV commands

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#27]
### Repository

Mops-Bot

### Bug type

Slash Commands

### Description of the bug?

on error interaction message, username for mention is undefined. 

### Relevant log output

```shell
[antiCrash] :: Unhandled Rejection/Catch
TypeError: Cannot read properties of undefined (reading 'username')
    at ttvConfig (B:\DEVELOPMENT\Mops-Bot\SlashCommandFunctions\trackers\ttv\ttvConfig.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (B:\DEVELOPMENT\Mops-Bot\SlashCommands\trackers\tracker.js:104:25) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'username')
      at ttvConfig (B:\DEVELOPMENT\Mops-Bot\SlashCommandFunctions\trackers\ttv\ttvConfig.js:21:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.run (B:\DEVELOPMENT\Mops-Bot\SlashCommands\trackers\tracker.js:104:25)
}
```

**Comment by OnlyTunes** [comment]
Found and implemented a fix in latest commit!

https://github.com/OnlyTunesRadio/Mops-Bot/commit/3eb7263eaf6ed242ed8e32207d6e4d55ee386349
