### ISSUE TITLE
Music commands ( LL Server issue )

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#67]
### Repository

Mops-Bot

### Bug type

Slash Commands

### Description of the bug?

LL Throwing errors

**Comment by OnlyTunes** [comment]
```

reject Promise {,
 [antiCrash] :: Multiple Resolves,
  <rejected> SyntaxError: Unexpected token  in JSON at position 0,
      at JSON.parse (<anonymous>),
      at Y.json (/usr/src/app/node_modules/petitio/dist/index.js:30:574),
      at ke.json (/usr/src/app/node_modules/petitio/dist/index.js:30:2499),
      at runMicrotasks (<anonymous>),
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
} Error: Query not found.,
    at Manager.<anonymous> (/usr/src/app/node_modules/erela.js/dist/structures/Manager.js:150:31),
    at Generator.next (<anonymous>),
    at fulfilled (/usr/src/app/node_modules/erela.js/dist/structures/Manager.js:5:58),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (node:internal/process/task_queues:96:5),
 [antiCrash] :: Unhandled Rejection/Catch
```

**Comment by OnlyTunes** [comment]
issue fixed as is running fine on beta version now
