### ISSUE TITLE
Api Causes errors with fetch

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#7]
### Repository

Mops-Bot-API

### Bug type

Other

### Description of the bug?

Api responds with a mix of text and json which causes fetch to have issues

### Additional information

All endpoints need to be changes to respond with json and not text! including ping

### Relevant log output

```shell
FetchError: invalid json response body at https://domain.com/mops/dsc/prefix/817543985056841728 reason: Unexpected token N in JSON at position 0
    at C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\mops-api-wrapper\node_modules\node-fetch\lib\index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Api.getCall (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\mops-api-wrapper\src\api.js:48:16)
    at async Dsc.getPrefix (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\node_modules\mops-api-wrapper\src\dsc.js:9:16)
    at async customPrefix (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\events\messageCreate.js:11:22)
    at async Client.<anonymous> (C:\Users\brayd\Desktop\DEVELOPMENT\Mops-Bot\events\messageCreate.js:23:23) {
  type: 'invalid-json'
}
```

**Comment by OnlyTunes** [comment]
slowly converting all responses to JSON only
